-- [Prog] SQL - lv4: 그룹별 조건에 맞는 식당 목록 출력하기

-- LEFT(): 왼쪽에서부터 문자열 자르기
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, LEFT(R.REVIEW_DATE, 10)
FROM MEMBER_PROFILE M
    INNER JOIN REST_REVIEW R
    ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1
    )
ORDER BY R.REVIEW_DATE

-- DATE_FORMAT(): 날짜 포맷 설정
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE M
    INNER JOIN REST_REVIEW R
    ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1
    )
ORDER BY R.REVIEW_DATE