-- [Prog] SQL - lv4: 보호소에서 중성화한 동물

-- 1.
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O
    LEFT JOIN ANIMAL_INS I
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND O.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY O.ANIMAL_ID

-- 2.
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O
    LEFT JOIN ANIMAL_INS I
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.SEX_UPON_OUTCOME NOT LIKE I.SEX_UPON_INTAKE
ORDER BY O.ANIMAL_ID