-- [Prog] SQL - lv2: 상품 별 오프라인 매출 구하기
SELECT P.PRODUCT_CODE, SUM(P.PRICE * AMOUNT) AS SALES
FROM PRODUCT P
    INNER JOIN (
        SELECT PRODUCT_ID, SALES_AMOUNT AMOUNT
        FROM OFFLINE_SALE
    ) S ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SUM(P.PRICE * AMOUNT) DESC, PRODUCT_CODE ASC