-- [Prog] SQL - lv4: 식품분류별 가장 비싼 식품의 정보 조회하기
SELECT A.CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT A
    INNER JOIN (
        SELECT CATEGORY, MAX(PRICE) MXP
        FROM FOOD_PRODUCT
        WHERE CATEGORY='과자' OR CATEGORY='국' OR CATEGORY='김치' OR CATEGORY='식용유'
        GROUP BY CATEGORY
    ) B ON B.MXP = A.PRICE AND B.CATEGORY = A.CATEGORY
ORDER BY PRICE DESC